name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Install Expo & EAS
        run: |
          npm install -g expo-cli eas-cli

      - name: Login to Expo
        run: eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Build APK
        run: |
          cd frontend
          eas build -p android --non-interactive --profile preview
